apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: estela-postgres-pvc
  namespace: estela
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ceph-rbd
  resources:
    requests:
      storage: 10Gi
