apiVersion: v1
kind: ServiceAccount
metadata:
  name: estela-deployer
  namespace: estela
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: estela-job-manager
  namespace: estela
rules:
  - apiGroups: ["", "batch"]
    resources: ["pods", "pods/log", "jobs", "jobs/status", "configmaps", "secrets"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: estela-job-manager-binding
  namespace: estela
subjects:
  - kind: ServiceAccount
    name: estela-deployer
    namespace: estela
roleRef:
  kind: Role
  name: estela-job-manager
  apiGroup: rbac.authorization.k8s.io
