apiVersion: v1
kind: Secret
metadata:
  name: estela-secrets
  namespace: estela
type: Opaque
stringData:
  secret-key: "lumiscrape-estela-insecure-secret-key-change-me"
  db-password: "estelapassword"
  database-url: "postgres://estela:estelapassword@estela-postgres:5432/estela"
