apiVersion: apps/v1
kind: Deployment
metadata:
  name: lumiscrape
  namespace: lumiscrape
  labels:
    app: lumiscrape
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lumiscrape
  template:
    metadata:
      labels:
        app: lumiscrape
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 65532
        runAsGroup: 65532
      containers:
        - name: lumiscrape
          image: ghcr.io/aobaiwaki123/lumiscrape:v1.0.0
          imagePullPolicy: IfNotPresent
          args: ["serve", "--port", "8080", "--host", "0.0.0.0"]
          ports:
            - containerPort: 8080
              name: http
          env:
            - name: LUMISCRAPE_LOG_LEVEL
              value: "info"
            - name: LUMISCRAPE_S3_ENDPOINT
              value: "minio.minio.svc.cluster.local:9000"
            - name: LUMISCRAPE_S3_BUCKET
              value: "lumiscrape-raw"
          resources:
            requests:
              cpu: 10m
              memory: 32Mi
            limits:
              cpu: 100m
              memory: 128Mi
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 3
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 2
            periodSeconds: 10
