apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: lumiscrape-ingress
  namespace: lumiscrape
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    cert-manager.io/cluster-issuer: letsencrypt-cloudflare
spec:
  ingressClassName: "cloudflare-tunnel"
  rules:
    - host: lumiscrape.aooba.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: lumiscrape
                port:
                  number: 8080
